services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d local']
      interval: 2s
      timeout: 5s
      retries: 20
volumes:
  pgdata:
